import type { StickerData, StickerTypes } from "./types";

export const STICKER_TYPE_MAP: Record<StickerTypes, StickerData> = {
  "chequered-flag": {
    type: "lottie",
    rarity: "unique",
    name: "Chequered Flag",
    unlockedBy: "Reading the earliest blog post",
    url: "/static/lottie/chequered-flag.json",
    initialFrame: 0,
  },
  clap: {
    type: "lottie",
    rarity: "common",
    name: "Clap",
    url: "/static/lottie/clap.json",
    initialFrame: 0,
  },
  dragon: {
    type: "lottie",
    rarity: "common",
    name: "Dragon",
    url: "/static/lottie/dragon.json",
    initialFrame: 60,
  },
  fire: {
    type: "lottie",
    rarity: "common",
    name: "Fire",
    url: "/static/lottie/fire.json",
    initialFrame: 0,
  },
  "glowing-star": {
    type: "lottie",
    rarity: "unique",
    name: "Glowing Star",
    unlockedBy: "Reading the latest blog post",
    url: "/static/lottie/glowing-star.json",
    initialFrame: 50,
  },
  goose: {
    type: "lottie",
    rarity: "unique",
    name: "Goose",
    unlockedBy: "Clicking the goose",
    url: "/static/lottie/goose.json",
    initialFrame: 0,
  },
  "light-bulb": {
    type: "lottie",
    rarity: "common",
    name: "Light bulb",
    url: "/static/lottie/light-bulb.json",
    initialFrame: 130,
  },
  lizard: {
    type: "lottie",
    rarity: "common",
    name: "Lizard",
    url: "/static/lottie/lizard.json",
    initialFrame: 0,
  },
  "party-popper": {
    type: "lottie",
    rarity: "common",
    name: "Party popper",
    url: "/static/lottie/party-popper.json",
    initialFrame: 25,
  },
  rainbow: {
    type: "lottie",
    rarity: "common",
    name: "Rainbow",
    url: "/static/lottie/rainbow.json",
    initialFrame: 50,
  },
  smile: {
    type: "lottie",
    rarity: "common",
    name: "Smile",
    url: "/static/lottie/smile.json",
    initialFrame: 100,
  },
  "thumbs-up": {
    type: "lottie",
    rarity: "common",
    name: "Thumbs up",
    url: "/static/lottie/thumbs-up.json",
    initialFrame: 60,
  },
  turtle: {
    type: "lottie",
    rarity: "common",
    name: "Turtle",
    url: "/static/lottie/turtle.json",
    initialFrame: 0,
  },
};
